apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-rollouts-demo
  namespace: demo
spec:
  replicas: 3 # 定义3个副本
  strategy: # 定义升级策略
    canary: # 金丝雀发布
      steps: # 发布的节奏
        - setWeight: 20
        - pause: {} # 会一直暂停,需要手动 promote
        - setWeight: 40
        - pause: { duration: 10 } # 暂停10s
        - setWeight: 60
        - pause: { duration: 10 }
        - setWeight: 80
        - pause: { duration: 10 }
  revisionHistoryLimit: 2 # 下面部分其实是和 Deployment 兼容的
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: registry.cn-hangzhou.aliyuncs.com/zhdya/kubernetes-bootcamp:v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
