apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: newapp-rollout-0902
  namespace: demo
spec:
  replicas: 3
  strategy:
    blueGreen:     
      activeService: bluegreen-appv1
      previewService: bluegreen-appv2
      # Rollouts can be resumed using: `kubectl argo rollouts promote ROLLOUT`      
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web
        image: registry.cn-hangzhou.aliyuncs.com/zhdya/kubernetes-bootcamp:v1
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
